export const STAFF = {
    FETCH_STAFF: 'FETCH_STAFF',
    GET_STAFF_MEMBERS: 'GET_STAFF_MEMBERS',
    NEW_STAFF:'NEW_STAFF',
    DELETE_STAFF_MEMBER: 'DELETE_STAFF_MEMBER',
    AUTH: 'AUTH',
    GET_USER: 'GET_USER',
    UPDATE_ACCOUNT: 'UPDATE_ACCOUNT',
}

export const REQUESTS = {
    FETCH_REQUESTS: 'FETCH_REQUESTS',
    GET_REQUEST: 'GET_REQUEST',
}

export const STATS = {
    FETCH_STATS: 'FETCH_STATS',
}

export const MQTT = {
    CREATE_CLIENT: 'CREATE_CLIENTE',
    // CONNECT: 'CONNECT',
    SEND_MESSAGE: 'SEND_MESSAGE',
    STATUS: 'STATUS'

}
